title: My Blog
author: Nick Booher

description: Software security and other things.

theme: minima

plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Specific pages for site navigation.
#header_pages:
#  - about.md

# Set to `true` to show excerpts on the homepage.
show_excerpts: true

github_username: njbooher
linkedin_username: njbooher